version: '3.9'
services:
    backend:
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: umarche
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33066:3306
